### ISSUE TITLE
[Request] Support save, delete

### ISSUE THREAD

**Issue by inspector71** [martinchrzan/FileExplorerGallery#2]
I understand this project's scope may only be for viewing. However, given how poor the default Windows viewers, and Explorer itself, are ... it would be great to be able to use basic editing options with this impressive tool. Such as:

1. Saving ... after rotating an image
2. Delete key ... to help people trawl through and remove unwanted files

Thank you for all the hard work and skill invested in this project. The long-running ability of individual developers to usurp the paltry efforts of big data giant corporations, with quality basic utilities for the operating systems they dare to charge for, is alive and well :)

**Comment by martinchrzan** [comment]
@inspector71 thanks a lot for suggestions, they actually make sense to speed up process when you want to quickly view and filter images! 
I will have a look into this.

**Comment by wilburlikesmith** [comment]
Long shot... Support for Total Commander?

**Comment by martinchrzan** [comment]
@inspector71 requested functionality is now available with the 1.1.0 version! 
@wilburlikesmith please create a separate issue for this as I am closing this one. It would not be impossible, but it will require me to write a standalone extension for total commander (I don't know how much work that would be) which would have to be installed along with my app so it is not any low hanging fruit unfortunately. Also interaction could be tricky as you have 2 folders opened there and you would need to choose which one should be used for the gallery.

**Comment by inspector71** [comment]
Wow, woohooo!

How do I access the settings?

Ah, the right-click menu in the system tray icon.
